// Jarvis-native MCP tools.
//
// Each tool here exposes existing Jarvis functionality through the MCP
// registry so external projects, Claude Desktop, and Claude Code can call
// them with bearer-token auth + per-tool scope checks.
//
// Pattern: thin wrappers that import existing lib code, never duplicate
// logic. If a tool needs new behaviour, build it in src/lib/<domain>/
// and call from here.

import { z, registerTool } from "@/lib/mcp/server"
import { getAllMemories, saveMemory, type MemoryType } from "@/lib/memory/store"
import { getAccountGated, getPositionsGated } from "@/lib/data/gated"
import { getSourceQualitySnapshot } from "@/lib/sandbox/quality"
import { safeFetch } from "@/lib/sandbox/whitelist"
import { db } from "@/lib/db/client"

// ── memory.search ──────────────────────────────────────────────
// Returns recent memories, optionally filtered by tag. Uses the existing
// store helper to avoid drifting from what the dashboard sees.
registerTool({
  name: "memory.search",
  description: "Search Jarvis's persistent memory. Returns recent memories ordered by importance and last access, optionally filtered by a tag (typically a ticker symbol).",
  inputSchema: z.object({
    tag: z.string().optional().describe("Optional tag filter, e.g. 'TSLA'"),
    limit: z.number().int().min(1).max(200).default(20),
  }),
  requiredScope: "read:memory",
  handler: async (input: { tag?: string; limit: number }) => {
    const all = await getAllMemories(input.limit * 4)  // over-fetch then filter
    const filtered = input.tag
      ? all.filter(m => m.tags.includes(input.tag!.toUpperCase()))
      : all
    return filtered.slice(0, input.limit).map(m => ({
      id: m.id,
      type: m.type,
      content: m.content,
      tags: m.tags,
      importance: m.importance,
      source: m.source,
      created_at: m.created_at,
    }))
  },
})

// ── signals.list ──────────────────────────────────────────────
// Returns recent rows from the signals table (entry signals pushed by
// trading_bot or generated by Jarvis itself).
registerTool({
  name: "signals.list",
  description: "List recent trading signals. Each signal includes the instrument, direction, entry, stop, target, confidence, and current status.",
  inputSchema: z.object({
    limit: z.number().int().min(1).max(100).default(20),
    status: z.enum(["pending", "filled", "cancelled", "expired"]).optional(),
  }),
  requiredScope: "read:signals",
  handler: async (input: { limit: number; status?: string }) => {
    const r = input.status
      ? await db.execute({
          sql: `SELECT id, strategy_id, instrument, direction, entry, stop, target,
                       confidence, status, created_at
                FROM signals WHERE status = ?
                ORDER BY created_at DESC LIMIT ?`,
          args: [input.status, input.limit],
        })
      : await db.execute({
          sql: `SELECT id, strategy_id, instrument, direction, entry, stop, target,
                       confidence, status, created_at
                FROM signals
                ORDER BY created_at DESC LIMIT ?`,
          args: [input.limit],
        })
    return r.rows.map(row => row as unknown as Record<string, unknown>)
  },
})

// ── account.snapshot ──────────────────────────────────────────
// Gated account + positions snapshot. Uses the same source-quality wrapper
// as the voice route so low-confidence data is signalled to the caller.
registerTool({
  name: "account.snapshot",
  description: "Get a current snapshot of the Alpaca paper-trading account: equity, buying power, day P&L, and open positions. Includes a confidence score so callers can detect stale or degraded data.",
  inputSchema: z.object({}),
  requiredScope: "read:account",
  handler: async () => {
    const [accountR, positionsR] = await Promise.all([
      getAccountGated(),
      getPositionsGated(),
    ])
    return {
      account: accountR.data ?? null,
      account_confidence: accountR.confidence,
      positions: Array.isArray(positionsR.data) ? positionsR.data : [],
      positions_confidence: positionsR.confidence,
    }
  },
})

// ── memory.save ───────────────────────────────────────────────
// Append a new memory. Importance 1-10 (default 5). Source defaults to
// 'system' which makes it clear an MCP client wrote this.
registerTool({
  name: "memory.save",
  description: "Save a new memory to Jarvis's persistent store. Use for facts, insights, patterns, or preferences that should survive across conversations.",
  inputSchema: z.object({
    content: z.string().min(1).max(2000),
    type: z.enum(["fact", "insight", "pattern", "preference", "correction"]).default("fact"),
    tags: z.array(z.string()).default([]),
    importance: z.number().int().min(1).max(10).default(5),
  }),
  requiredScope: "write:memory",
  handler: async (input: { content: string; type: MemoryType; tags: string[]; importance: number }) => {
    const id = await saveMemory(input.content, input.type, {
      tags: input.tags,
      importance: input.importance,
      source: "system",
    })
    return { id, ok: true }
  },
})

// ── source_quality.snapshot ───────────────────────────────────
// Current source confidence table — same data the /source-quality dashboard
// renders. Useful for clients to detect degraded feeds before reasoning.
registerTool({
  name: "source_quality.snapshot",
  description: "Get the current source quality table — per-source confidence, 24h pass rate, and last fetch time. Sources with confidence < 0.5 are quarantined (stripped from LLM context).",
  inputSchema: z.object({}),
  requiredScope: "read:account",  // same scope as account — observability surface
  handler: async () => {
    const snapshot = await getSourceQualitySnapshot()
    const quarantined = snapshot.filter(s => s.last_confidence < 0.5)
    return {
      sources: snapshot,
      quarantined_count: quarantined.length,
      threshold: 0.5,
    }
  },
})

// ── voice.ask ─────────────────────────────────────────────────
// Routes a query through Jarvis's voice handler. Lets MCP clients pose
// natural-language questions and get Jarvis's full reasoning + market
// context applied. Implemented as an HTTP call to the existing /api/voice
// route so we don't duplicate the pipeline.
registerTool({
  name: "voice.ask",
  description: "Ask Jarvis a question and get the full voice-pipeline response — runs through market context, memories, research, and the LLM chain. Returns the spoken text.",
  inputSchema: z.object({
    query: z.string().min(1).max(2000),
    chartSymbol: z.string().optional().describe("If the user is viewing a specific chart, pass the ticker here for richer context."),
  }),
  requiredScope: "read:account",  // voice exposes account data in responses
  handler: async (input: { query: string; chartSymbol?: string }) => {
    const base = process.env.NEXT_PUBLIC_APP_URL ?? "https://jarvis-system-flame.vercel.app"
    const r = await safeFetch(`${base}/api/voice`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ query: input.query, chartSymbol: input.chartSymbol }),
      signal: AbortSignal.timeout(45_000),
    })
    if (!r.ok) {
      return { ok: false, status: r.status, error: await r.text().catch(() => "voice route error") }
    }
    const data = await r.json()
    return {
      ok: true,
      response: data.response,
      tickers: data.tickers ?? [],
      action: data.action ?? null,
    }
  },
})
