// Jarvis-native MCP tools.
//
// Each tool here exposes existing Jarvis functionality through the MCP
// registry so external projects, Claude Desktop, and Claude Code can call
// them with bearer-token auth + per-tool scope checks.
//
// Pattern: thin wrappers that import existing lib code, never duplicate
// logic. If a tool needs new behaviour, build it in src/lib/<domain>/
// and call from here.

import { z, registerTool } from "@/lib/mcp/server"
import { getAllMemories } from "@/lib/memory/store"
import { getAccountGated, getPositionsGated } from "@/lib/data/gated"
import { db } from "@/lib/db/client"

// ── memory.search ──────────────────────────────────────────────
// Returns recent memories, optionally filtered by tag. Uses the existing
// store helper to avoid drifting from what the dashboard sees.
registerTool({
  name: "memory.search",
  description: "Search Jarvis's persistent memory. Returns recent memories ordered by importance and last access, optionally filtered by a tag (typically a ticker symbol).",
  inputSchema: z.object({
    tag: z.string().optional().describe("Optional tag filter, e.g. 'TSLA'"),
    limit: z.number().int().min(1).max(200).default(20),
  }),
  requiredScope: "read:memory",
  handler: async (input: { tag?: string; limit: number }) => {
    const all = await getAllMemories(input.limit * 4)  // over-fetch then filter
    const filtered = input.tag
      ? all.filter(m => m.tags.includes(input.tag!.toUpperCase()))
      : all
    return filtered.slice(0, input.limit).map(m => ({
      id: m.id,
      type: m.type,
      content: m.content,
      tags: m.tags,
      importance: m.importance,
      source: m.source,
      created_at: m.created_at,
    }))
  },
})

// ── signals.list ──────────────────────────────────────────────
// Returns recent rows from the signals table (entry signals pushed by
// trading_bot or generated by Jarvis itself).
registerTool({
  name: "signals.list",
  description: "List recent trading signals. Each signal includes the instrument, direction, entry, stop, target, confidence, and current status.",
  inputSchema: z.object({
    limit: z.number().int().min(1).max(100).default(20),
    status: z.enum(["pending", "filled", "cancelled", "expired"]).optional(),
  }),
  requiredScope: "read:signals",
  handler: async (input: { limit: number; status?: string }) => {
    const r = input.status
      ? await db.execute({
          sql: `SELECT id, strategy_id, instrument, direction, entry, stop, target,
                       confidence, status, created_at
                FROM signals WHERE status = ?
                ORDER BY created_at DESC LIMIT ?`,
          args: [input.status, input.limit],
        })
      : await db.execute({
          sql: `SELECT id, strategy_id, instrument, direction, entry, stop, target,
                       confidence, status, created_at
                FROM signals
                ORDER BY created_at DESC LIMIT ?`,
          args: [input.limit],
        })
    return r.rows.map(row => row as unknown as Record<string, unknown>)
  },
})

// ── account.snapshot ──────────────────────────────────────────
// Gated account + positions snapshot. Uses the same source-quality wrapper
// as the voice route so low-confidence data is signalled to the caller.
registerTool({
  name: "account.snapshot",
  description: "Get a current snapshot of the Alpaca paper-trading account: equity, buying power, day P&L, and open positions. Includes a confidence score so callers can detect stale or degraded data.",
  inputSchema: z.object({}),
  requiredScope: "read:account",
  handler: async () => {
    const [accountR, positionsR] = await Promise.all([
      getAccountGated(),
      getPositionsGated(),
    ])
    return {
      account: accountR.data ?? null,
      account_confidence: accountR.confidence,
      positions: Array.isArray(positionsR.data) ? positionsR.data : [],
      positions_confidence: positionsR.confidence,
    }
  },
})
